openapi: 3.0.1
info:
  title: k8s-job-chief
  description: service for starting and tracking k8s jobs
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /states:
    get:
      operationId: getStates
      tags:
        - states
      summary: get the statistics about all existing queues
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/queueStatistics'
components:
  schemas:
    queueStatistics:
      type: object
      additionalProperties:
        type: object
        properties:
          created:
            type: integer
          retry:
            type: integer
          active:
            type: integer
          completed:
            type: integer
          expired:
            type: integer
          cancelled:
            type: integer
          failed:
            type: integer
          all:
            type: integer
