{{- $releaseName := .Release.Name -}}
{{- $chartName := include "job-chief.name" . -}}
{{- $cloudProviderFlavor := include "job-chief.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "job-chief.cloudProviderDockerRegistryUrl" . -}}
{{- $imageTag := include "job-chief.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "job-chief.environment" . }}
    release: {{ $releaseName }}
    {{- include "job-chief.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "job-chief.selectorLabels" . | nindent 6 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "job-chief.selectorLabels" . | nindent 8 }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
    {{- if .Values.cloudProvider.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.cloudProvider.imagePullSecretName | quote }}
    {{- end }}
      serviceAccountName: {{ $releaseName }}-{{ $chartName }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            {{- if .Values.caSecretName }}
            - name: REQUESTS_CA_BUNDLE
              value: '/usr/local/share/ca-certificates/ca.crt'
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
            - secretRef:
                name: {{ $releaseName }}-{{ $chartName }}-secret
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.targetPort }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: jobs-configmap
              mountPath: /etc/config
          {{- if and .Values.caSecretName .Values.caKey }}
            - mountPath: '/usr/local/share/ca-certificates'
              name: root-ca
              subPath: {{ quote .Values.caKey }}
          {{- end }}
          {{- if .Values.dbConfig.sslAuth.enabled }}
            - name: cert-conf
              mountPath: /tmp/certs
              readOnly: true
          {{- end }}
      volumes:
        - name: jobs-configmap
          configMap:
            name: {{ .Release.Name }}-{{ $chartName }}-jobs-configmap
        {{- if and .Values.caSecretName .Values.caKey }}
        - name: root-ca
          secret:
            secretName: {{ .Values.caSecretName }}
        {{- end }}
        {{- if .Values.dbConfig.sslAuth.enabled }}
        - name: cert-conf
          secret:
            secretName: {{ .Values.dbConfig.sslAuth.secretName }}
        {{- end }}
{{- end -}}
